### PR TITLE
Disable logging by default

### LINKED ISSUE #1: Can't use `--print-id` with variable assignment
Using GNU Bash 4.4 on Ubuntu 18.04 (yes, legacy system, but still supported due to Ubuntu Pro, so... :shrug: I assume newer versions are affected as well) I can't use `--print-id` to assign the notification's ID to a variable.

The following works as expected:
```console
$ src/notify-send.sh --print-id Test
Warning: The notification service on your device doesn't support
         hyperlinks in it's body text. So they will be filtered out.
Warning: The notification service on your device doesn't support
         images in it's body text. So they will be filtered out.
91
```

However, assigning the output (i.e. the notification's ID) to a variable fails:
```console
$ FOO="$(src/notify-send.sh --print-id Test)"
src/notify-send.sh: 70: …/src/notify-common.d/setup.sh: cannot create /proc/21236/fd/pipe:[60224718]: Directory nonexistent
Warning: The notification service on your device doesn't support
         hyperlinks in it's body text. So they will be filtered out.
Warning: The notification service on your device doesn't support
         images in it's body text. So they will be filtered out.
```

The issue seems to be that you expect `/proc/$$/fd/1` and `/proc/$$/fd/2` (`$FD1` and `$FD2` variables in `./src/notify-common.d/setup.sh`, lines 40+41) to always link to a path. However, this isn't true when the script's output is assigned to a variable; it's some magic value like `pipe:[60224718]` then.

I'm not entirely sure whether all this shell magic in `./src/notify-common.d/setup.sh` is even necessary? :thinking: It seems like (I'm not entirely sure though) that this (i.e. redirecting `stdout` and `stderr` to a logfile and then printing it again) is solely used for debugging purposes. Why not wrap the whole logfile logic in `if $LOGGING; then …; fi`? That's exactly what I did locally and nothing seems to break. See pull request #2

System info:
```console
$ bash --version
GNU bash, Version 4.4.20(1)-release (x86_64-pc-linux-gnu)
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux dev 5.4.0-187-generic #207~18.04.1-Ubuntu SMP Thu Jun 13 15:01:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Off topic: Is there any other way to disable the warnings than piping `stderr` to `/dev/null`?

### PR DESCRIPTION
**Pull request by PhrozenByte**
Since `notify-send.sh` doesn't run as a service but on invocation only, the only purpose logging serves is debugging the script's usage (not necessarily the script itself, pass the `DEBUG=true` env variable for that). Permanently enabling logging causes `notify-send.sh` to constantly create logfiles that serve no purpose unless the user is actively trying to debug the script's usage. Thus it's better to enable logging only when logging was requested by the user. To enable logging, pass the `LOGGING=true` env variable.

Another reason to disable logging by default is that it breaks assigning the script's output (e.g. the notification ID with `--print-id`) to a variable on some platforms. See #1

Closes #3

### CODE REVIEW

**Comment by PhrozenByte** [comment]
Rebased on #3 (i.e. either merge just this PR and close #3, or merge #3 first and then this one - doesn't matter as long as you don't squash-merge)

Please note that this doesn't actually fix #1, but rather puts the issue behind an env variable.

**Comment by M3TIOR** [comment]
@PhrozenByte Thanks for the PR! Really surprised anyone is interested in my little fork TBH and a little peeved that I never got notified by GH's notification system or their email relay about this sooner. Your criticism of the logging is valid, the main logs generated by the program are extraneous most of the time. Though I could have sworn I'd made the logging infrastructure only output logs to stderr so data capture wouldn't break. I'll double check that. I'll also take a look at your other modifications

**Comment by M3TIOR** [comment]
You know what that is rather silly, I don't know what I was thinking with the file logging for a non-daemon. Goober alert.

**Comment by PhrozenByte** [comment]
> Really surprised anyone is interested in my little fork TBH

Sure, why not? Some minor issues shouldn't hide the fact that you did a great job here. Making `notify-send.sh` POSIX-compliant is no small feat :+1:

> You know what that is rather silly, I don't know what I was thinking with the file logging for a non-daemon. Goober alert.

Just wanna point out that I wouldn't have even noticed these logfiles if `--print-id` hadn't been broken. They generally don't do harm, they just coincidentally do. I just figured that putting them behind a `LOGGING` env variable similar to the existing `DEBUG` env variable is both justifiable IMHO and solves the `--print-id` issue for now.

Thanks for merging! :+1:

**Pull request merged**
